name: Deploy to Cloud Run Job

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  id-token: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Print GitHub context
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Owner: ${{ github.repository_owner }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/479134170399/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
        service_account: ledger-deployer@ledger-457022.iam.gserviceaccount.com
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Run a simple command to verify authentication
      run: gcloud info
    
    - name: Create and run a Cloud Run job
      run: |
        echo "Creating a Cloud Run job..."
        gcloud beta run jobs create simple-job-${{ github.run_id }} \
          --image=gcr.io/google-samples/hello-app:1.0 \
          --region=us-east4 \
          --project=ledger-457022
        
        echo "Executing the job..."
        gcloud beta run jobs execute simple-job-${{ github.run_id }} \
          --region=us-east4 \
          --project=ledger-457022 