name: Deploy "ledger" to Cloud Run

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Debug repository info
      run: |
        echo "GitHub Repository: ${{ github.repository }}"
        echo "Expected: sku3397/ledger-cfo"
        echo "Branch: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Event Name: ${{ github.event_name }}"
    
    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/479134170399/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
        service_account: ledger-deployer@ledger-457022.iam.gserviceaccount.com
        token_format: access_token
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Debug GCP authentication
      run: |
        echo "Checking GCP authentication status..."
        gcloud auth list
        gcloud config list
        echo "List projects to verify auth is working..."
        gcloud projects list --limit=5
    
    - name: Deploy directly to Cloud Run
      run: |
        echo "Deploying directly to Cloud Run using source-based deployment..."
        gcloud run deploy ledger \
          --source=. \
          --platform=managed \
          --region=us-east4 \
          --project=ledger-457022 \
          --allow-unauthenticated
    
    - name: Check deployment status
      run: |
        echo "Checking Cloud Run service status..."
        gcloud run services describe ledger \
          --platform=managed \
          --region=us-east4 \
          --project=ledger-457022
        
        echo "Getting service URL..."
        SERVICE_URL=$(gcloud run services describe ledger \
          --platform=managed \
          --region=us-east4 \
          --project=ledger-457022 \
          --format="value(status.url)")
        
        echo "Service URL: $SERVICE_URL"
        
        if [ -n "$SERVICE_URL" ]; then
          echo "Checking if service is accessible..."
          curl -s "$SERVICE_URL" || echo "Could not curl the service URL"
        else
          echo "Service URL not available."
        fi 