name: Deploy "ledger" to Cloud Run

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Verify environment
      run: |
        echo "GitHub Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo "Commit SHA: ${{ github.sha }}"
    
    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/479134170399/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
        service_account: ledger-deployer@ledger-457022.iam.gserviceaccount.com
        token_format: access_token
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Debug GCP authentication
      run: |
        echo "Checking GCP authentication status..."
        gcloud auth list
        gcloud config list
        echo "List projects to verify auth is working..."
        gcloud projects list --limit=5
    
    - name: Verify Artifact Registry repository
      run: |
        echo "Checking if Artifact Registry repository exists..."
        REPO_EXISTS=$(gcloud artifacts repositories describe cfo-agent-repo --location=us-east4 --project=ledger-457022 2>&1 || echo "NOT_FOUND")
        if [[ $REPO_EXISTS == *"NOT_FOUND"* ]]; then
          echo "Creating Artifact Registry repository..."
          gcloud artifacts repositories create cfo-agent-repo --repository-format=docker --location=us-east4 --description="Docker repository for CFO Agent" --project=ledger-457022
        else
          echo "Artifact Registry repository already exists."
          gcloud artifacts repositories list --project=ledger-457022 --location=us-east4
        fi
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-east4-docker.pkg.dev --quiet
        echo "Docker authentication configured"
    
    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:latest .
        docker images
    
    - name: Push Docker image
      run: |
        echo "Pushing Docker image to Artifact Registry..."
        docker push us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:latest
        echo "Verifying image was pushed..."
        gcloud artifacts docker images list us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo --project=ledger-457022 --limit=5
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ledger
        image: us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:latest
        region: us-east4
    
    - name: Check deployment status
      if: always()
      run: |
        echo "Deployment status: ${{ steps.deploy.outcome }}"
        echo "Service URL: ${{ steps.deploy.outputs.url }}"
        gcloud run services list --platform=managed --region=us-east4 --project=ledger-457022
    
    - name: Display service URL
      if: steps.deploy.outputs.url != ''
      run: |
        echo "Service URL: ${{ steps.deploy.outputs.url }}"
        curl -s ${{ steps.deploy.outputs.url }} || echo "Could not curl the service URL" 