name: Deploy "ledger" to Cloud Run

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/479134170399/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
        service_account: ledger-deployer@ledger-457022.iam.gserviceaccount.com
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Verify repository path
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Expected: Matt/CFO_Agent"
    
    - name: Verify Artifact Registry repository
      run: |
        echo "Checking if Artifact Registry repository exists..."
        REPO_EXISTS=$(gcloud artifacts repositories describe cfo-agent-repo --location=us-east4 --project=ledger-457022 2>&1 || echo "NOT_FOUND")
        if [[ $REPO_EXISTS == *"NOT_FOUND"* ]]; then
          echo "Creating Artifact Registry repository..."
          gcloud artifacts repositories create cfo-agent-repo --repository-format=docker --location=us-east4 --description="Docker repository for CFO Agent" --project=ledger-457022
        else
          echo "Artifact Registry repository already exists."
        fi
    
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-east4-docker.pkg.dev
    
    - name: Build and Push Container
      run: |
        echo "Building Docker image..."
        docker build -t us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:latest -t us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:${{ github.sha }} .
        echo "Pushing Docker image to Artifact Registry..."
        docker push us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:latest
        docker push us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ledger
        image: us-east4-docker.pkg.dev/ledger-457022/cfo-agent-repo/ledger:latest
        region: us-east4
        
    - name: Display service URL
      run: |
        echo "Service URL: ${{ steps.deploy.outputs.url }}" 